-- MySQL Script generated by MySQL Workbench
-- Fri Apr 17 09:41:12 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Players
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Players
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Players` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Players` ;

-- -----------------------------------------------------
-- Table `Players`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Players`.`Player` (
  `PlayerID` INT NOT NULL,
  `Name` VARCHAR(100) NULL,
  `Credits` VARCHAR(100) NULL,
  `LifetimeSpins` INT NOT NULL AUTO_INCREMENT,
  `SaltValue` VARCHAR(50) NULL,
  PRIMARY KEY (`PlayerID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
