-- MySQL Script generated by MySQL Workbench
-- Thu Apr 16 11:41:39 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema spinCollections
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spinCollections
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spinCollections` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `spinCollections` ;

-- -----------------------------------------------------
-- Table `spinCollections`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spinCollections`.`Player` (
  `PlayerID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Credits` INT NULL,
  `LifetimeSpins` INT NULL,
  `SaltValue` INT NULL,
  PRIMARY KEY (`PlayerID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
